### ISSUE TITLE
caution message and missing icons after NC update

### ISSUE THREAD

**Issue by nephilim75** [strukturag/nextcloud-spreedme#71]
Hello

I ran Spreed.Me app on NC 11.0.0 without any issues. I folloewd the given steps in [this guide](https://github.com/strukturag/nextcloud-spreedme) and it worked perfectly fine.

Today I updated NC to vers. 11.0.1 via updater app. This worked fine so far, but after enabling the Spreed.Me app it is showing the the following:

![spreed_nc1101](https://cloud.githubusercontent.com/assets/19992865/22403146/e9f831c8-e60e-11e6-8ac6-d1c850f609ad.PNG)

The message means, _that I shall logon to create rooms_. I am logged in as you can see. Also, there are missing several icons (red marked area) which were visible before I updated to NC 11.0.1.

Any idea what happend and how I can get this fixed?

Kind regards
//neph

**Comment by nephilim75** [comment]
Got it solved. Config got lost during update process. Re-configured: /var/www/nextcloud/apps/spreedme/config/config.php & cd /var/www/nextcloud/apps/spreedme/extra/static/config/OwnCloudConfig.js

**Comment by leonklingele** [comment]
Configuring the app via files is still supported, but as you have seen this will lead to problems after upgrading the app.
Since version 0.3.0 you can also configure the app via the Nextcloud Admin web interface: https://github.com/strukturag/nextcloud-spreedme/commit/6a9b74afc3a9abb805378f29a41ff992b2f48bc9#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5
This way, you don't need to restore the files after an upgrade.
